stages:
  - build
  - deploy

image: "$CI_DOCKER_REGISTRY/esp-idf-doc-env:v4.4-1-v2"

variables:
  # System environment

  # Common parameters for the 'make' during CI tests
  MAKEFLAGS: "-j5 --no-keep-going"

  # GitLab-CI environment
  GET_SOURCES_ATTEMPTS: "10"
  ARTIFACT_DOWNLOAD_ATTEMPTS: "10"
  GIT_SUBMODULE_STRATEGY: none

  ESP_IDF_GIT: "https://gitlab-ci-token:${CI_JOB_TOKEN}@${GITLAB_HTTPS_SERVER}/espressif/esp-idf.git"

.add_gh_key_remote: &add_gh_key_remote |
  command -v ssh-agent >/dev/null || exit 1
  eval $(ssh-agent -s)
  printf '%s\n' "${GH_PUSH_KEY}" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh && chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config || ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  git remote remove github || true
  git remote add github ${GH_PUSH_REPO}

after_script:
  # Just for cleaning space, no other causes
  - git clean -ffdx


# This template gets expanded multiple times, once for every IDF version.
# IDF version is specified by setting the espressif/idf image tag.
#
# EXAMPLE_TARGETS sets the list of IDF_TARGET values to build examples for.
# It should be equal to the list of targets supported by the specific IDF version.
#
# TEST_TARGETS sets the list of IDF_TARGET values to build the test_app for.
# It should contain only the targets with optimized assembly implementations.
#
.build_template:
  stage: build
  tags:
    - build
    - internet
  script:
    - ./build_all.sh
  variables:
    EXAMPLE_TARGETS: "esp32"
    TEST_TARGETS: "esp32"

build_idf_v4.0:
  extends: .build_template
  image: espressif/idf:release-v4.0

build_idf_v4.1:
  extends: .build_template
  image: espressif/idf:release-v4.1

build_idf_v4.2:
  extends: .build_template
  image: espressif/idf:release-v4.2
  variables:
    EXAMPLE_TARGETS: "esp32 esp32s2"

build_idf_v4.3:
  extends: .build_template
  image: espressif/idf:release-v4.3
  variables:
    EXAMPLE_TARGETS: "esp32 esp32s2 esp32c3"

build_idf_latest:
  extends: .build_template
  image: espressif/idf:latest
  variables:
    EXAMPLE_TARGETS: "esp32 esp32s2 esp32s3 esp32c3"
    TEST_TARGETS: "esp32 esp32s3"

build_docs:
  stage: build
  tags:
    - build_docs
  artifacts:
    when: always
    paths:
      - docs/doxygen-warning-log.txt
      - docs/sphinx-warning-log.txt
      - docs/_build/html
    expire_in: 1 day
  # No cleaning when the artifacts
  after_script: []
  script:
    - dir
    - source /opt/pyenv/activate
    - dir
    - pyenv global $(pyenv versions --bare)
    - dir
    - cd docs
    - dir
    - python -m pip install -r requirements.txt
#    - python ./build_docs.py -bs $DOC_BUILDERS -l $DOCLANG -t $DOCTGT build
    - dir 
    - make html
    - dir
    - ./check_doc_warnings.sh

push_master_to_github:
  stage: deploy
  tags:
    - deploy
  only:
    - master
    - /^release\/v/
    - /^v\d+\.\d+(\.\d+)?($|-)/
  when: on_success
  script:
    # Just for a helper script
    - git clone --depth 1 ${ESP_IDF_GIT} esp-idf
    - *add_gh_key_remote
    - esp-idf/tools/ci/push_to_github.sh
